
import "../globals.css";


import Footer from "../components/footer"
import Nav2 from "../components/nav2";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="w-full h-screen flex flex-col">
        <div>
          <Nav2/>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
